<?php

    // TEM QUE APAGAR ESSA MERDA DO GIT
    // MAS SEMPRE VOLTA

    // TEM QUE APAGAR ESSA MERDA DO GIT
    // MAS SEMPRE VOLTA

    // TEM QUE APAGAR ESSA MERDA DO GIT
    // MAS SEMPRE VOLTA

    // TEM QUE APAGAR ESSA MERDA DO GIT
    // MAS SEMPRE VOLTA

    // TEM QUE APAGAR ESSA MERDA DO GIT
    // MAS SEMPRE VOLTA

    // TEM QUE APAGAR ESSA MERDA DO GIT
    // MAS SEMPRE VOLTA

?>
